title: Cheulyoung Park
author: Cheul Young Park
email: cheulyop@kaist.ac.kr
description: | # this means to ignore newlines until "baseurl:"
  Master's Student of KSE @ KAIST
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal